name: Actions

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7, 3.9, '3.10']
        r-version: ['release']
        exclude:
        - os: windows-latest
          python-version: '3.10'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --prefer-binary -r requirements-dev.txt
        Rscript build/requirements.R
    - name: Lint with pylint
      run: |
        python -m pylint --fail-under=9.5 circa/ tests/
    - name: Smoke test
      run: python -m circa.experiment -h
    - name: Unit tests
      run: python -m coverage run && python -m coverage report
    - name: Benchmark
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.9
      run: python -m pytest --benchmark-only --disable-pytest-warnings tests/
